version: "3.9"
services:
  mysql-container:
    container_name: mysql-container
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 200978
      MYSQL_DATABASE: user_service
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres-container:
    container_name: postgres-container
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 200978
      POSTGRES_DB: course_service
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  user-service:
    container_name: user-service
    image: marcosramos20/user:latest
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql-container:3306
      DB_DATABASE: user_service
      DB_USERNAME: root
      DB_PASSWORD: 200978
      CURSOS_URL: course_service:8002
    networks:
      - spring
    depends_on:
      - mysql-container
    restart: always

  course-service:
    container_name: course-service
    image: marcosramos20/course:latest
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres-container:5432
      DB_DATABASE: course_service
      DB_USERNAME: postgres
      DB_PASSWORD: 200978
      USUARIOS_URL: course_service:8001
    networks:
      - spring
    depends_on:
      - postgres-container
      - user-service
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
